/* ============================================================
   Malspaß — everything Klecks says (DE/EN)

   Plain JSON between the markers, so tools/make_voices.py can read
   it and record every line with ElevenLabs. The key is the file
   name: audio/de-<key>.mp3 and audio/en-<key>.mp3.
   Lines without a recording are read by the device voice.
   ============================================================ */
window.Mal.LINES = /* LINES-JSON */ {
  "red":          { "de": "Rot", "en": "Red" },
  "orange":       { "de": "Orange", "en": "Orange" },
  "yellow":       { "de": "Gelb", "en": "Yellow" },
  "green":        { "de": "Grün", "en": "Green" },
  "blue":         { "de": "Blau", "en": "Blue" },
  "purple":       { "de": "Lila", "en": "Purple" },
  "pink":         { "de": "Rosa", "en": "Pink" },
  "brown":        { "de": "Braun", "en": "Brown" },
  "black":        { "de": "Schwarz", "en": "Black" },
  "white":        { "de": "Weiß", "en": "White" },
  "clean":        { "de": "Alles sauber!", "en": "All clean!" },
  "lang":         { "de": "Deutsch", "en": "English" },
  "hello":        { "de": "Hallo! Ich bin Klecks, ein kleiner Farbklecks. Malst du mit mir?", "en": "Hello! I'm Klecks, a little blob of paint. Will you paint with me?" },
  "hi":           { "de": "Hallo!", "en": "Hi there!" },
  "letsGo":       { "de": "Los geht's!", "en": "Let's go!" },
  "newThing":     { "de": "Schau mal! Da ist etwas Neues!", "en": "Look! Something new!" },
  "sleeps1":      { "de": "Noch einmal schlafen!", "en": "One more sleep!" },
  "sleeps2":      { "de": "Noch zweimal schlafen!", "en": "Two more sleeps!" },
  "sleeps3":      { "de": "Noch dreimal schlafen!", "en": "Three more sleeps!" },
  "sleepsN":      { "de": "Noch ein paar Mal schlafen!", "en": "A few more sleeps!" },
  "ch_free":      { "de": "Tipp auf eine Farbe und mal mit dem Finger!", "en": "Tap a color and paint with your finger!" },
  "ch_rainbow":   { "de": "Ein Regenbogen-Pinsel! Alle Farben auf einmal!", "en": "A rainbow brush! All the colors at once!" },
  "ch_stamps":    { "de": "Stempel! Tipp, tipp, tipp: ein Stern, ein Herz, eine Blume!", "en": "Stamps! Tap, tap, tap: a star, a heart, a flower!" },
  "ch_mirror":    { "de": "Ein Zauberspiegel! Was du auf einer Seite malst, kommt auch auf die andere. Wie bei einem Schmetterling!", "en": "A magic mirror! What you paint on one side appears on the other side too. Just like a butterfly!" },
  "ch_night":     { "de": "Es ist Nacht, und deine Farben leuchten! Mal den Mond und die Sterne!", "en": "It's night time, and your colors glow! Paint the moon and the stars!" },
  "ch_mix":       { "de": "Heute mischen wir Farben! Was passiert, wenn Rot und Gelb sich treffen?", "en": "Let's mix colors! What happens when red and yellow meet?" },
  "circle":       { "de": "Kreis", "en": "Circle" },
  "square":       { "de": "Quadrat", "en": "Square" },
  "triangle":     { "de": "Dreieck", "en": "Triangle" },
  "star":         { "de": "Stern", "en": "Star" },
  "heart":        { "de": "Herz", "en": "Heart" },
  "flower":       { "de": "Blume", "en": "Flower" },
  "soMuch":       { "de": "So viel", "en": "So much" },
  "manyColors":   { "de": "So viele Farben!", "en": "So many colors!" },
  "fridge":       { "de": "Das kommt an den Kühlschrank!", "en": "That goes on the fridge!" },
  "fridgeEmpty":  { "de": "Der Kühlschrank ist noch leer. Komm, wir malen was!", "en": "The fridge is still empty. Come on, let's paint something!" },
  "sleepy":       { "de": "Ich werde langsam müde. Noch ein letztes Bild!", "en": "I'm getting sleepy. One last picture!" },
  "goodnight":    { "de": "Das war schön! Jetzt mache ich ein kleines Nickerchen. Bis bald!", "en": "That was lovely! Now I'm going to have a little nap. See you soon!" },
  "goodnightDay": { "de": "Das war schön heute! Jetzt schlafe ich. Bis morgen!", "en": "That was lovely today! Now I am going to sleep. See you tomorrow!" },
  "realPaint":    { "de": "Mal doch mit echten Stiften weiter!", "en": "Why not keep painting with real crayons?" },
  "awake":        { "de": "Ausgeschlafen! Wollen wir malen?", "en": "I'm all rested! Shall we paint?" },
  "st_colors":    { "de": "Mein Malkasten ist größer geworden! Jetzt gibt es auch Orange, Lila, Rosa und Braun.", "en": "My paint box got bigger! Now there's orange, purple, pink and brown too." },
  "st_sizes":     { "de": "Dicke und dünne Pinsel! Probier mal ganz dünn – und dann ganz dick.", "en": "Thick and thin brushes! Try really thin – and then really thick." },
  "st_eraser":    { "de": "Ein Radiergummi! Damit kannst du etwas wieder wegmachen und neu malen.", "en": "An eraser! You can take something away and paint it again." },
  "st_brushes":   { "de": "Neue Pinsel! Wachsmalstift, Wasserfarbe und Filzstift. Jeder malt ein bisschen anders.", "en": "New brushes! Crayon, watercolor and marker. Each one paints a little differently." },
  "st_bucket":    { "de": "Ein Farbeimer! Tipp in eine Fläche, dann wird sie bunt. Und der Pfeil geht einen Schritt zurück.", "en": "A paint bucket! Tap inside a shape and it fills with color. And the arrow goes one step back." },
  "st_shades":    { "de": "Hell und dunkel! Jede Farbe gibt es jetzt heller und dunkler.", "en": "Light and dark! Now every color comes lighter and darker." },
  "tool_paint":   { "de": "Fingerfarbe", "en": "Finger paint" },
  "tool_crayon":  { "de": "Wachsmalstift", "en": "Crayon" },
  "tool_water":   { "de": "Wasserfarbe", "en": "Watercolor" },
  "tool_marker":  { "de": "Filzstift", "en": "Marker" },
  "tool_eraser":  { "de": "Radiergummi", "en": "Eraser" },
  "tool_bucket":  { "de": "Farbeimer", "en": "Paint bucket" },
  "size_s":       { "de": "Dünn", "en": "Thin" },
  "size_m":       { "de": "Mittel", "en": "Medium" },
  "size_l":       { "de": "Dick", "en": "Thick" },
  "shade_light":  { "de": "Hell", "en": "Light" },
  "shade_normal": { "de": "Kräftig", "en": "Bold" },
  "shade_dark":   { "de": "Dunkel", "en": "Dark" },
  "tellMe":       { "de": "Erzähl mal: Wie hast du das gemalt?", "en": "Tell me: how did you paint that?" }
} /* /LINES-JSON */;
