/* Recorded clips in audio/ — generated by tools/make_voices.py, do not edit by hand. */
self.MAL_CLIPS = {
  "de": [
    "black",
    "blue",
    "brown",
    "clean",
    "green",
    "lang",
    "orange",
    "pink",
    "purple",
    "red",
    "white",
    "yellow"
  ],
  "en": [
    "black",
    "blue",
    "brown",
    "clean",
    "green",
    "lang",
    "orange",
    "pink",
    "purple",
    "red",
    "white",
    "yellow"
  ]
};
